### ISSUE TITLE
route problem when refershing navigationbar

### ISSUE THREAD

**Issue by youkaisteve** [MonkeyKingPlus/react-native-router#1]
Hi

I'm using react-native-router in my app.It really helps me a lot.
I found a problem when I was using it yesterday. There is a 'TabView' in my app with the router, it has two tabs named 'tab1' and 'tab2',  tab1 is the first scene.The navigationBar of the scene in the tab2 should be updated when navigating to the scene.But the whole 'TabView' was refreshed and focused to tab1 while the current scene was focused in tab2. I guess that the route has been refreshed while refreshing navigationBar.

Please check it out,thanks!

**Comment by m860** [comment]
fixed this problem in version 1.4.7
